# Generated by Django 3.1.7 on 2021-05-13 02:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemaker',
            name='date',
            field=models.CharField(default=datetime.date(2021, 5, 13), max_length=100),
        ),
    ]
