# Generated by Django 3.1.7 on 2021-03-15 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100, null=True, verbose_name='name of the event')),
                ('event_type', models.CharField(choices=[('technical', 'technical'), ('cultural', 'cultural'), ('sports', 'sports')], default='technical', max_length=15, null=True, verbose_name='event type')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('event_team', models.CharField(choices=[('Computer society of India', 'Computer society of India'), ('Matrix club', 'Matrix club'), ('ACM Student chapter', 'ACM Student chapter'), ('bits n bytes', 'bits n bytes'), ('IEEE', 'IEEE'), ('C2S2', 'C2S2'), ('Epic student club', 'Epic student club'), ('mechstein club', 'mechstein club'), ('ASME', 'ASME'), ('water society', 'water society'), ('NSS', 'NSS'), ('NCC', 'NCC')], max_length=30, null=True, verbose_name='Team organising')),
            ],
        ),
        migrations.CreateModel(
            name='file_upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventYear', models.IntegerField(choices=[('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028')], null=True, verbose_name='year of the event')),
                ('fileupload', models.FileField(upload_to='csv')),
                ('eventName', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='upload.events', verbose_name='event name')),
            ],
        ),
    ]
