# Generated by Django 3.1.7 on 2021-03-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('types', models.CharField(choices=[('student contribution', 'student contribution'), ('teacher contribution', 'teacher contribution'), ('student awards', 'student awards'), ('teacher awards', 'teacher awards'), ('custom', 'custom'), ('events', 'events')], max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
